### ISSUE TITLE
Session.connect: java.security.NoSuchAlgorithmException: DH KeyPairGenerator not available

### ISSUE THREAD

**Issue by neilyoung** [mucommander/JRE#1]
Hi,

I'm fetching this error with 0.9.3 while trying to connect to a public/private key authenticated SFTP server. I'm able to provide username and private key file in settings, but connect fails with this error.

**Comment by ahadas** [comment]
@neilyoung can you please try with [this version](https://github.com/mucommander/mucommander/releases/download/0.9.3-3/mucommander-0.9.3.dmg)?

**Comment by neilyoung** [comment]
@ahadas Yes, great. That works again. Thanks for fixing so fast.

Regards
